---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kanidm-tcp
  namespace: admin
spec:
  entryPoints:
    - websecure
  tls:
    passthrough: true
  routes:
    - match: HostSNI(`idm.${domain}`)
      services:
        - name: kanidm
          port: 8443
