apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: envoy-pocket-id-client-secret
    namespace: admin
data:
    client-secret: ENC[AES256_GCM,data:cfdaNqwBWwaCFK4IGlnVLd4tXAv2AAwzaZbcXUEP/Qbe6dOSl9xG2k0d29Y=,iv:46XSD9Q9BUvU9vErGdqK8KkmUBck5ak4HzGej3yze1U=,tag:xCfH8/KI1yzaIwaiyi8Ftg==,type:str]
sops:
    lastmodified: "2025-11-13T18:24:31Z"
    mac: ENC[AES256_GCM,data:/FY/Sm8W51QrtW1lV0RVhm/SfbL0ZilT6sTHk9rH6IT48J1GfPyCAEC6falxkJ3+TroTxa5XtJzk8Q/nCzXWsm7KDb869Z/O1BZ6dN5JqomV9W4FTxex2N/KkPddP+vJ2hT1qL9c4RUSH2ooWluKoSHCx4Tz1WUIOTw2FH7hy8M=,iv:bgIxqG6Dk7wj7jtakmbAXOlbON33lqY4T4B+FXEG/VM=,tag:UTKR2lFbSO7sO1K8sifwhQ==,type:str]
    pgp:
        - created_at: "2025-11-13T18:24:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf/eGJ6tKjbK1JIxT69/FEBKP+2Re/EL/WpQpXqzskpQE65
            Usv9LCqRVeVFU0Hp5UBtmSFhS1A+nNj+FQUPApb1v2kxWbTtUN8Ey2NER4c75p1q
            RoNKrg+lUkOIJjz8lC7N6ADThP5seWNOnymkK2+ecCQBRlXZse/XLWrJcQGKy37X
            O99Ia+Q6ItZ7q6a7aULcP59QH9vwaaQz24Qtn4U0YC1mFcZx9WCBAPkadogLl+gM
            Ieq4dH5MfcftH5cDZ15+dko01tKOtU9j7/uv6lvzxfhnD1RSFch3SDtoFJ0lpRG8
            aFWWYtB2of0fgDEad3SCSSiJpOpExnlX7uc4pdvLQtJeAW2OOunwxFkvzGcxCMqP
            +TPA40FeEfrreOCZxKe0BpVNlqOyCGL3qHHIdcqpdE6uYVThqGI3UhGEoALUBA2H
            MO6xGvKrwTGMSaq1TXabvpqQxdI4TuopfnJcxquEcA==
            =NllA
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2025-11-13T18:24:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0AQ//Uh+InkOFRyOOv5laGwngcM+SVNVuDgYCyUkvMOsx0OVW
            jM3V4J6NJgq28ONWrtSoEyAE/nYblUTBL1zlFoBgBDAuGbVi6z8OHuEA9zhd0aKe
            r5VJQ412COMRMBSmg1Pz45+QGJ6aXokeJoqmgDTYsmdSyCt2OLHfICAiS3kRcVd3
            HyTYGS9zJcsQCASSq+oQPMFNmhMYhFWdLkkZh1FU0pW56Nj1MKC58uH+8j0QTk7D
            pf+MKsQ0Yx9sDx0o30aSJZ297PaPK+S6d0+jXXQL++EkHvqKqFX/dLq2jv5NWzFN
            dszRAOmg831u96ka1KVR6zWS7ZVOxOlIAzobnZGkXslB9qo/TsoshoRG/DLv0DKP
            TzOaBXDB8yVcBFHifXp70bghGd1xMtjt06LTNJU4Mhywdu4Y97NuIKZvcZySDYjk
            oiy8wQaVfGBlcXLgGjtfSCRgqdbl0R7615Uej1WsRw8mErO0QnlmhSf9D6fWpga8
            NgdAxwGuIyjbGnm0W1c39QQluLQwlNTKa8s8ZS4F2kNKQ1JuHznnOXSXVyZi32ee
            RJesTIeHKy08JqqtkNKJaiTHwkzcoGik/JC9epp7xwClM1iKvZi92gUlf6qOsofq
            BoRTV3Fo+RDkJyI1gI4RYAJyvJifFg/HRF75pGVgHHgk+TfILTQbEEkwUtIDWNfS
            XgGg9OhuuktUEJsd/I0ZoroOzhTWszZh6CnTLN1/beBFe8lrxEYdTStAnBrudDRl
            LJAB3hQX4zRpFoGY5rBzRisgX1LlDPv/Fr1aHDzrrdECn4up+iwz21aeAJr7xYc=
            =WlPU
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2025-11-13T18:24:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ/6Alv6icBBGLq8cNQ422rKPxjhogYdHaBE7Emua9YfNhU0
            +hKd+T4oVeHG24sDp5qFMojaHSArJdU++0QPPacFdTAeg6huIDNzvl3Ngv9g0qto
            l9OuFpNdCMabvZ60oFrWKfVXMJiKfuGwl3wuL4iuTyggdPsuSzKT7k6Z8V9nd7ja
            GP5SCFvDzG7ibCPA5ZdxUu2PqwBTMy6mnecNJhnNgrKtXT6ScpSAzKNhIeRF2nW7
            ZEKtQ7CF8Jw4Hz52gNd4FtbhDOHt80rBfZOXDcXZ76PTA+TFbR4dt4DzvzgO5ikQ
            MSd5xkidrD3mfFRMPxaNS31lskzRylFgw39qUAaE+hDhDeYGfKEK1PQpnx4T+ual
            FEnRjvl4LZcoWmJq35PIliiCBwGgD6Ug3+ukqk78lgwiVQpHad8IGrkB6klAGX8V
            Pe2zqAJdjMvbCzFLyYrt847ixEFz8CHEVj5G1RjGt8gnhwSMixbu7LNs74q1nhGh
            QZmKp4G/doEgdX9xnej4Kd69qkcTjKGNrBjqDI4deJ2F3rxKZ/q24m4V2ZkUib3T
            1sS0dg/APgd4d98DqVzzTQRkl29lqooCFWgFO+i4trie6v+bSBuJND5QN0qoWDrY
            hBQU304g2v0cRmACNBiI6axFIgrinhiVoS2jFqQelSXjBcO2iQd7YA3wrfOpuO/S
            XgHtxQJL5cP4aKixsfGwhTLNw4nTrwUmXNXe1WqO1uFFIeICu9bQ3bhD+dMDqxS3
            JRaU5+saSiYy8FXxB4bTKMa/ORsShxrLOEO8Qj/uJgeBdsXL/iFT5O7ayxFN93k=
            =d6z6
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
        - created_at: "2025-11-13T18:24:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DGePB2r9HxYkSAQdAdEX9gGi8EGMQWQ6AfxWuMpHbAIMy1gkMyTv/FtFRgD0w
            GWfVGEMtqWgBFGk36QBn+K6XVdDWMwFUKU12q9FQnl11SzZOE8oSJRH/rS2+KTBd
            0l4B3/aoHgblLFuPJS3rNgrtfFFiNdwrURq/yZ3rKzdGejibPmmROe3VAp30iIJA
            wIt6lKi+pXszYKtmSj8Sd5+BPiwhYT2LDgf/KT8jDgJeL9RCiULuWT6eEDE9NYuK
            =58h6
            -----END PGP MESSAGE-----
          fp: 5A3F5D11B86C085EAAC7F0B54136591338099DBA
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
