---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr
  - plex
  - radarr
  - sonarr
  - prowlarr
  - flaresolverr
  - jellyfin
  - qbittorrent
  - music-assistant
  - cleanuparr
  - qui
  - calibre
  - shelfmark
