version: "3.5"
services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /homelab/dockerregistry:/var/lib/registry
    networks:
      - webnet

  joshwolfe:
    image: 127.0.0.1:5000/joshwolfe.ca:latest
    depends_on:
      - registry
    networks:
      - webnet
    deploy:
      labels:
        - traefik.backend=joshwolfe
        - traefik.frontend.rule=Host:joshwolfe.ca
        - traefik.port=1313
        - traefik.docker.network=webnet
        - traefik.frontend.redirect.entryPoint=https

networks:
  webnet:
    external: true
