---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nvidia-smi-exporter
  namespace: nvidia
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-smi-exporter
  podMetricsEndpoints:
    - port: metrics
