kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: authelia-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

spec:
  rules:
    - host: login.dev.joshwolfe.ca
      http:
        paths:
          - backend:
              serviceName: authelia
              servicePort: 80
