---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaniop
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chartRef:
    kind: OCIRepository
    name: kaniop
    namespace: flux-system
