version: "3"
services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      TZ: 'EST5EDT'
      OTHER_ARGS: '--ping-exit 60'
    networks:
      - webnet
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    dns: 1.1.1.1
    volumes:
      - /dev/net:/dev/net:z
      - /home/wolfe/surfshark/nl-ams.prod.surfshark.com_udp.ovpn:/vpn/config.ovpn
    env_file:
      - ~/.torrent.env

  transmission:
    image: linuxserver/transmission
    depends_on:
      - vpn
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    network_mode: "service:vpn"
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - /homelab/transmission/config:/config:Z
      - /homelab/transmission/downloads:/downloads:Z
      - /homelab/transmission/watch:/watch:Z

  #nzbget:
  #  image: linuxserver/nzbget
  #  depends_on:
  #    - vpn
  #  environment:
  #    - PUID=1002
  #    - PGID=1003
  #    - TZ=America/New_York
  #  network_mode: "service:vpn"
  #  stdin_open: true
  #  tty: true
  #  volumes:
  #    - /homelab/nzbget/config:/config:Z
  #    - /homelab/nzbget/downloads:/downloads:Z
  #  labels:
  #    - traefik.backend=nzbget
  #    - traefik.docker.network=webnet
  #    - traefik.port=6789
  #    - traefik.frontend.rule=Host:nzbget.${domain}

networks:
  webnet:
    external: true
