---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: pomerium
  namespace: pomerium
spec:
  gatewayClassName: pomerium-gateway
  listeners:
    - name: https
      hostname: "*.joshwolfe.ca"
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: "${domain/./-}-tls"
      allowedRoutes:
        namespaces:
          from: All
