---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/pomerium/ingress-controller/config/default?ref=v0.31.0
  - pomerium.yaml
  - oidc-secret.sops.yaml
  - envoy-admin.yaml
patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: pomerium-proxy
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--debug-admin-addr=localhost:9901"
    target:
      kind: Deployment
      name: pomerium
