apiVersion: v1
kind: Secret
metadata:
    name: oidc-secret
    namespace: pomerium
stringData:
    client_id: ENC[AES256_GCM,data:dKbSC8T4oDIj3cpISUxF40ljDDQzLabzxjEENXzZREi/fROW,iv:SMmkE1brNNWU5rhjKKUg70FkgKYryNjxe2xGMM9cloc=,tag:M8BOlx1V/Zd7ERm7tyN4QQ==,type:str]
    client_secret: ENC[AES256_GCM,data:Kn9vfOqxNLTmpMSyAOqJvi+P3hlYGkMlnkJfyV3EH5g=,iv:K+g2ODvAqUyF9VPJJqmGj920/aD6UXHXa0x8KWn//fE=,tag:U9hqn1iw+lrra2IvNPFTeA==,type:str]
sops:
    lastmodified: "2025-11-20T20:41:38Z"
    mac: ENC[AES256_GCM,data:DMELlGqqbrXCeGGhZ47xPA5dyAXeY9KVi3mRvPBdssZdGAwcQZTGL04DUl4ogf7z/3UARutQKIPls4+AS5S7XCgsAWNkv4Of39wP0y6y9LsKuStFNDJoC0cZv1H2ZmISMbHqKsLcZGlSzWsjvrk/7b4luMLHHt7zMSvRyDGaRZg=,iv:dWNcZNR1Mi2Z0usY84tWQljrWeJguZKCB6iLwTs9KLg=,tag:f2fcBuZTVpvWFYBd3hpGtw==,type:str]
    pgp:
        - created_at: "2025-11-20T20:40:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf/VbGhwZLBDidv3lxJ6QWDuhTWd6bg4YzqLYi6rgxK5yOy
            ZPDfNb3uahlVWRoLFOZeTS8oXHvld2Q9/2PEGFqL371ai1D9iKPCpiHi53yqkAxQ
            gLzKYv4PKPGOKabCgCcNmejFJ4+NFHY6i6zs1NUVAC9qb6kiyqrKrAVIwIYvhnoq
            0O+kbqy0pRat2NgZ/9cElP0zo4gjBCqDVrQJZMPc66kC5x3poT9OmTrFdqrxgQKK
            X92CpZcmQxC3vS8iF/CUzhiJMPiYytkyqh8HfCFIGqewIqr1UwCABhwtlD0KnkGE
            Uv6UhSwlOYKFYdWOL2jnXKLsmnkB+gHG0vvjiz4EgtJeAZU795oYmwps7Lh3RTlq
            eVtViU9wYy+rS+w3pmrNUd6yPN+nrce9jk4+dk/7+sGZS9QbcYn4O2sRqazIfrMg
            4ejVAnEQIv+xUilIrZPyCkxrvrXhq+JyGYO3x5Q+3w==
            =SQMF
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2025-11-20T20:40:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0AQ//U5NJUGduc3Xfm2yMREJC6LfqpsPNhwlFkYkf1ha59tQY
            XhU8tTO46mlgD00D1bYFiOzjAdZHIU0+da8lwe9ICPSPZaP/7ua7GpgIA6Wxe4dk
            7++dKUMeWiVKwbS91g0YbVkHU6yxKChsN4+3ZVwZD15lyButTImG0Q/ROBVQfvSS
            GdDbWfp5NGk7ppCwhW9L5t0NP4GQFmmSipNHYZfC3O2a0jBX23QiEZBhczFWVUuL
            2xUugfvg2Omt7D1nlNAaTXy6LbEPz7nT6xnsi7Ebh7n6zbZrAxDQBbl5oSiJBJek
            dEuqlbzHDuutICm6bPyjJHoy449E0V5cLMwD/H3kXyhkatVmvlLp/8VL2lQqtfcc
            nfmRpvxqB2CJFimL7VQ8+H241WO7tgzTO0NKtQjHgeoA+7kBW/ht1J44sNAn7N5J
            otO6bhKoGeQdGF2fFinfQy/Pf811w+xaokwsXKoWQkuEAmN+GfM83KEv6KrXJQG9
            hQZIUtwlmREzx8V121vhMG8SIFoaXIiOTppCLppC+idx1Bz4eMtCDkFq7ky6hdWH
            +QGtqJ8Wzd1VwVtKFWjJyi2BqaoOf2eDJhVEuGGxfvbPaGaseDBNuCpNAkwX7KJn
            OlTNjbccNi5UeMpR0KJHi+wfieE2SbFEzy38q4nFb/wfKECosbXDygUs5Z7CFtvS
            XgGifPZU5vu8YhNyOi76YBhxcIpu4xwYwN69ryo88bJITOjVMUTeqW6+wS+Ui56t
            I6R2r28JN0yUySzpU1lAvrbaUBdsfO8FxINHnm/ixvQsJMnbHK7YZxM/c+NJrNE=
            =XH0a
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2025-11-20T20:40:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8ARAAlM4kekKcA6uIbKm6PkIRZXwMit7eT2I/J6jecenl8fSr
            cgmNXSFUtUvJ3VGe2wEff8mMgWLsf35HeU1LoVA3zfWFovLf+6UX7DKjFiV+206p
            bNQV8lN4ZMCcc/GqRonB4hRIEP3YFf1M202KvUyvTd66EmZ1ptXjNsmRzOXUNvHB
            2f3kJtGV2kL9g1Gw53XFKulICFQPgYwPKdKjFV3NEI1IAae4X+tTB13tqygivoEM
            vJ2p+NVvZha0Ui91mtJR57SbPAfqIQysaBpOW25QyIZNPH2ggYSkYyO7wYccKKEL
            LommO2lSqCi2kS2jgQUA3AYshQUDsoY4N/aNag/gBHMkxqysRBwQxNpbleD4c2BC
            5beU5RQexQLOFEkEDvl1L7rWjLC+gU3eOWKNkKqxFpbJdysZV5w86XNHX8mzgt4w
            CJ65BraMYBFk+ism8V2PBAu9WLBLsyRuECrJZrNApAg9c+zL/tVVw+oAOfrF3yCN
            xq1wSHwO6ELLyk7MGlrNrJxDuRAq06gqiiSCsqZ3mxYBAaDq3BXKtNww5nF/H5cR
            1x0TtZ1tPq/ClmXyvtxukPNsGFh4y2lgVhygBfG7AWS6+jCbejyzifM+9y5o24ib
            GyG/Pt+tXt1Nv2AoXpHeKjtODAOceF69pQ0ehRmFWWmAVBaIYq21mLpHKdTEWvDS
            XgG4XZdiWdp2c/Sd0WxjVURTzYotEEWzFnDyq56ihfolIWZW2ybyQevjYiMgMtek
            ae3aJ+Yuf5D0tSj8sZfOaU1/ruFyeQgTxTEikmicZRvyxO69JJiFVC05pmy0lbI=
            =0IEI
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
        - created_at: "2025-11-20T20:40:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DGePB2r9HxYkSAQdAl9xSLvAkBdrVdlR68GXm6wavoRX5gfFDbTRupt5T1AQw
            zF3evemUIW5g4E/XTGA+PRUWhoq3dhUug7lIBhzOZNnOCMLwrY9dHaxo6trUngD5
            0l4BryfgkGSC9E2j7B9dHhP/+DIt4RnvBsplJarkRtiQsn41hqUwdlSVn6znkbfa
            iwgNpZNvmUeE1/Kr7no246RLYi2Gw4egaRFRrTmszmHYf8pXWvgyu3NUM+YgzKtL
            =znj4
            -----END PGP MESSAGE-----
          fp: 5A3F5D11B86C085EAAC7F0B54136591338099DBA
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
